#!/bin/bash

# use KRNT as default airport unless something else is specified on cli args
if [ -z "$1" ]; then
  AIRPORT="KRNT"
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  cat << EOF
Usage: metar [airport code]
Example: metar KSEA
More at https://github.com/vsinha/METAR
EOF
  exit 1
else
  AIRPORT=$(awk '{print toupper($0)}' <<< $1)
fi

CURLURL="https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&stationString=$AIRPORT&hoursBeforeNow=1"

curl --silent $CURLURL | grep -oPm1 "(?<=<raw_text>)[^<]+"

